data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-retail-416720'
    dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: d1cf2311-d6b6-4edd-8f53-71a37e2f8c0b
  api_key_secret: wgXfno_yjt4s1jyiW0cBbn4zwAdQLlTjswcIlwURJFmlzo9-II6ghg